Add whitespace after period
ElrondNetwork/docs.elrond.com pull request #104
Opened 2021-04-25 02:05 UTC by rootulp

#### Description of the pull request (what is new / what has changed)
Add whitespace after period

#### Did you test the changes locally ?
- [ ] yes
- [x] no

#### Which category(categories) does this pull request belong to?
- [ ] document new feature
- [ ] update documentation that is not relevant anymore
- [ ] add examples or more information about a component
- [x] fix grammar issues
- [ ] other

2021-05-14 08:08 UTC, miiu96 approved these changes

2021-05-25 12:48 UTC, bogdan-rosianu requested changes
Please target this PR to `external` branch

2021-05-25 16:20 UTC, rootulp commented
@bogdan-rosianu done

2021-05-26 09:11 UTC, bogdan-rosianu approved these changes

2021-05-26 09:20 UTC, raduchis approved these changes

2021-05-26 09:23 UTC, merged