Inline comments for hex encoded data
ElrondNetwork/docs.elrond.com pull request #106
Opened 2021-04-25 02:16 UTC by rootulp

#### Description of the pull request (what is new / what has changed)
Makes this section slightly more readable

#### Did you test the changes locally ?
- [ ] yes
- [x] no

#### Which category(categories) does this pull request belong to?
- [ ] document new feature
- [ ] update documentation that is not relevant anymore
- [ ] add examples or more information about a component
- [ ] fix grammar issues
- [x] other

2021-05-25 12:48 UTC, bogdan-rosianu requested changes
please target this PR to `external` branch

2021-05-25 16:19 UTC, rootulp commented
@bogdan-rosianu done.

2021-05-26 09:11 UTC, bogdan-rosianu approved these changes

2021-05-26 09:19 UTC, raduchis approved these changes

2021-05-26 09:22 UTC, merged