Mandos update
ElrondNetwork/docs.elrond.com pull request #202
Opened 2021-09-29 10:16 UTC by andrei-marinica

#### Description of the pull request (what is new / what has changed)

#### Did you test the changes locally ?
- [x ] yes
- [ ] no

#### Which category(categories) does this pull request belong to?
- [ x] document new feature
- [ x] update documentation that is not relevant anymore
- [ x] add examples or more information about a component
- [ ] fix grammar issues
- [ ] other

2021-09-29 11:02 UTC, andrei-diaconescu requested changes

2021-09-29 11:02 UTC, andrei-diaconescu commented on docs/developers/mandos-reference/values-simple.md
> +On Elrond, smart contract addresses have a different format than user addresse - they start with 8 bytes of zero.
typo

2021-09-29 12:21 UTC, dorin-iancu commented on docs/developers/mandos-reference/values-complex.md
> +                "str:lotteryInfo|nested:str:lottery_name": {
It is :)

2021-09-29 12:21 UTC, dorin-iancu commented on docs/developers/mandos-reference/values-complex.md
> +- lists have their length explicitly encoded at the start.
Maybe a small note here about how all lengths are encoded on 4 bytes

2021-09-29 12:22 UTC, dorin-iancu commented
Great work :tada:

2021-09-30 06:32 UTC, dorin-iancu approved these changes

2021-09-30 06:33 UTC, andrei-diaconescu approved these changes

2021-09-30 06:34 UTC, merged