EN-12804: documented apr calculation
ElrondNetwork/docs.elrond.com pull request #398
Opened 2022-07-28 13:48 UTC by bogdan-rosianu

#### Description of the pull request (what is new / what has changed)
documentation about staking providers - APR computation

#### Did you test the changes locally ?
- [x] yes
- [ ] no

#### Which category (categories) does this pull request belong to?
- [ ] document new feature
- [ ] update documentation that is not relevant anymore
- [x] add examples or more information about a component
- [ ] fix grammar issues
- [ ] other

2022-08-04 16:16 UTC, AdoAdoAdo requested changes

2022-08-05 08:24 UTC, bogdan-rosianu commented on docs/validators/apr.md
> +set up. According to the initial deposits (half the price of a node) + delegations from other users (or even the owner itself)
fixed

2022-08-05 08:24 UTC, bogdan-rosianu commented on docs/validators/apr.md
> +the staking contract can spawn new nodes. Currently, a node costs 2500 EGLD, so, for example, if a staking contract
fixed

2022-08-05 08:25 UTC, bogdan-rosianu commented on docs/validators/apr.md
> +The upper difference is considered top-up. Also, the staking provider owner can choose to keep the tokens as top-up, even
fixed

2022-08-05 08:25 UTC, bogdan-rosianu commented on docs/validators/apr.md
> +As stated, a validator node requires 2500 EGLD. So multiple nodes would mean a number of tokens that is divisible by 2500.
fixed

2022-08-05 08:26 UTC, bogdan-rosianu commented on docs/validators/apr.md
> + | 1    | 10.84%         |
fixed

2022-08-05 08:27 UTC, bogdan-rosianu commented on docs/validators/apr.md
> +to be taken into account, such as total value locked at Network-level, the inflation based on the current year, and so on.
fixed

2022-08-05 08:27 UTC, bogdan-rosianu commented on docs/validators/apr.md
> +topUpRewards(e) = \frac{(2 * topUpRewardLimit(e)}{\pi} * atan(\frac{eligibleCumulatedTopUp(e)}{p})
fixed

2022-08-05 08:29 UTC, bogdan-rosianu commented on docs/validators/apr.md
> +- `topUpRewardLimit(e)` represents the maximum top-up rewards that can be distributed in the given epoch
the more details, the better. added

2022-08-05 08:29 UTC, bogdan-rosianu commented on docs/validators/apr.md
> +- `blocksRewards(e)` represents the rewards received by the validators by either signing or proposing blocks during the epoch that are now
fixed

2022-08-05 08:31 UTC, bogdan-rosianu commented on docs/validators/apr.md
> +First, we have to determine the maximum rewards that can be reached in ideal situations (no roll-back in an epoch).
fixed

2022-08-05 10:22 UTC, merged