Update adaptive-state-sharding.md
ElrondNetwork/docs.elrond.com pull request #44
Opened 2021-02-05 11:55 UTC by davidp94

#### Description of the pull request (what is new / what has changed)

#### Did you test the changes locally ?
- [x] yes
- [ ] no

#### Which category(categories) does this pull request belong to?
- [ ] document new feature
- [ ] update documentation that is not relevant anymore
- [ ] add examples or more information about a component
- [x] fix grammar issues
- [ ] other

2021-04-25 02:35 UTC, rootulp submitted a review, later dismissed
Thanks for fixing this typo!

2021-04-26 00:24 UTC, rootulp submitted a review, later dismissed

2021-05-25 13:09 UTC, bogdan-rosianu requested changes
please target this PR to `external` branch

2021-05-26 09:12 UTC, bogdan-rosianu approved these changes

2021-05-26 09:20 UTC, raduchis approved these changes

2021-05-26 09:23 UTC, merged